version: '3.8'

services:
  # Coldfusion Lucee NGINX Webserver
  lucee-nginx:
    container_name: tma-lucee-nginx-webserver
    build: 
      context: lucee
    image: lucee
    restart: unless-stopped
    domainname: "tma-app"
    depends_on:
      - mysql
    ports:
      - 9999:8888
      - 80:80
      - 443:443 # SSL
    volumes:
      - ./lucee/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./lucee/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./lucee/web/www:/var/www
      - ./mysql/schema.sql:/var/www/mysql/schema.sql
      - ./secrets/lucee_server_password.txt:/opt/lucee/server/lucee-server/context/password.txt
    networks: 
      - tma-app
    env_file: 
      - ./env/global.env
    secrets:
      - lucee_server_password
      - db_password

  mysql:
    container_name: tma-mysql
    build: 
      context: mysql
    image: mysql
    restart: always
    ports: 
      - 3307:3306
    volumes:
      - type: volume
        source: tma-data-volume
        target: /var/lib/mysql
    networks: 
      - tma-app
    env_file: 
      - ./env/mysql.env
      - ./env/global.env
    secrets:
      - db_root_password
      - db_password

  phpmyadmin:
    container_name: tma-phpmyadmin
    build: 
      context: phpmyadmin
    image: phpmyadmin
    restart: always
    depends_on: 
      - mysql
    networks: 
      - tma-app
    ports:
      - 99:99
    env_file: 
      - ./env/phpmyadmin.env
      - ./env/global.env

secrets:
  db_password:
    file: secrets/db_password.txt
  db_root_password:
    file: secrets/db_root_password.txt
  lucee_server_password:
    file: secrets/lucee_server_password.txt
  storage_account_key:
    file: secrets/storage_account_key.txt

networks: 
  tma-app:
    driver: bridge

volumes:
  tma-data-volume: